### ISSUE TITLE
Error: EMFILE, too many files open

### ISSUE THREAD

**Issue by ezze** [arloliu/copy-node-modules#9]
I encountered the following error using this module:

`Error: EMFILE: too many open files, open '/var/data/store/nfsshare/soft/copy-node-modules-emfile/node_modules/spdx-exceptions/README.md',Error: EMFILE: too many open files, open '/var/data/store/nfsshare/soft/copy-node-modules-emfile/dist/node_modules/spdx-exceptions/README.md',Error: EMFILE: too many open files, open '/var/data/store/nfsshare/soft/copy-node-modules-emfile/node_modules/spdx-exceptions/index.json'`

While everything works fine on Ubuntu 16.04 LTS on my local machine, I get the error on CentOS 7 on the server.

[Here](https://stackoverflow.com/q/8965606/506695) is a related question on StackOverflow. I [tried](https://github.com/ezze/copy-node-modules/commit/287e5cf4f79f542cbfdcfed78d9f37a7f5f9689b) to use [graceful-fs](https://github.com/isaacs/node-graceful-fs) instead of `fs` as it proposed there but it doesn't work.

I created a [repo](https://github.com/ezze/copy-node-modules-emfile) reproducing this issue.

**Comment by ezze** [comment]
Please, consider merging #10 to solve the issue.

**Comment by arloliu** [comment]
Thanks a lot

**Comment by ezze** [comment]
@arloliu, thanks for accepting it. Will you publish a new version to npm with the changes?
